services:
  api:
    image: rowjw/personal-portfolio-backend:test
    container_name: portfolio-backend
    ports:
      - "8000:8000"
    volumes:
      - portfolio-data:/src/assets
      - portfolio-db:/personal_portfolio_django/db

  web:
    image: rowjw/personal-portfolio-frontend:test
    container_name: portfolio-frontend
    ports:
      - "3000:3000"
    volumes:
      - portfolio-data:/src/assets
volumes:
  portfolio-data:
  portfolio-db:
