services:
  api:
    image: rowjw/personal-portfolio-backend:latest
    container_name: portfolio-backend
    networks:
      - caddy
    labels:
      caddy: api.rowanjefferywall.com
      caddy.reverse_proxy: '{{upstreams 8000}}'

  web:
    image: rowjw/personal-portfolio-frontend:latest
    container_name: portfolio-frontend
    networks:
      - caddy
    labels:
      caddy: rowanjefferywall.com
      caddy.reverse_proxy: '{{upstreams 3000}}'

networks:
  caddy:
    external: true
