version: '3.7'

services:
  db:
    image: postgres:12.20-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    hostname: db
    ports:
      - "5432:5432"
    env_file:
      - ./.env
  backend:
    volumes:
      - static:/app/personal_portfolio_django/static
      - media:/app/personal_portfolio_django/media
    build:
      context: ./api/personal_portfolio_django
    ports:
      - "8000:8000"
  frontend:
    build:
      context: ./frontend
    volumes:
      - frontend:/frontend/build
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - static:/static
      - frontend:/var/www/frontend
      - media:/media
    depends_on:
      - backend
      - frontend
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
volumes:
    static:
    frontend:
    postgres_data:
    media:
