# Generated by Django 5.0.7 on 2024-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0001_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.CharField(max_length=60, verbose_name='Image filename'),
        ),
        migrations.AlterField(
            model_name='project',
            name='url',
            field=models.CharField(blank=True, max_length=60, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='social',
            name='icon',
            field=models.CharField(max_length=60, verbose_name='FA Icon name'),
        ),
    ]
