# Generated by Django 5.0.7 on 2024-09-21 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_skill_image_alter_project_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_path',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
